# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: doughnut CI

on: push
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ARTIFACT: "doughnut"
  VERSION: "0.0.1-SNAPSHOT"
  GCS_BUCKET: "dough-01"

jobs:
  E2E-tests:
    name: End-to-End tests with Database
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        spec:
          - |
            cypress/integration/b*/**
          - |
            cypress/integration/c*/**
            cypress/integration/f*/**
            cypress/integration/u*/**
          - |
            cypress/integration/n*/**
          - |
            cypress/integration/r*/**
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'zulu'
          architecture: x64
      - name: Build frontend
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - name: End-to-End tests with Cypress
        uses: cypress-io/github-action@v2
        with:
          config: pageLoadTimeout=100000,video=false
          install-command: npm install
          start: npm run
          wait-on: "http://localhost:8080"
          spec: ${{ matrix.spec }}
